# Generated by Django 4.0.2 on 2022-02-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressbook",
            name="address",
            field=models.CharField(default="n/a", max_length=255),
        ),
    ]
