# Generated by Django 4.0.2 on 2022-02-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_addressbook_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressbook",
            name="postcode",
            field=models.CharField(default="00000", max_length=25),
        ),
    ]
