# Generated by Django 4.0.2 on 2022-02-02 13:29

import re

from django.db import migrations


def extract_postcode(apps, schema_editor):
    # We can't impor the AddressBook model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AddressBook = apps.get_model("address", "AddressBook")
    for address in AddressBook.objects.all():
        postcodes = re.findall(r"(?<!\d)\d{5}(?!\d)", address.address)
        if len(postcodes) > 0:
            address.postcode = postcodes[0]
        address.save()

def put_postcode_in_address(apps, schema_editor):
    # We can't impor the AddressBook model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AddressBook = apps.get_model("address", "AddressBook")
    for address in AddressBook.objects.all():
        address.address = f"... {address.postcode} ..."
        address.save()

class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_addressbook_postcode"),
    ]

    operations = [migrations.RunPython(extract_postcode, put_postcode_in_address)]
